######################################################################
# Pentestdb, a database for penetration test.
# Copyright (c) 2014-2015 alpha1e0
#===================================================
# java容器，服务器常用后台
######################################################################

# 注意每个java容器/服务器可能有多个不同功能的后台

glassfish:
- description: glassfish console
  port: 4848
  type: http
  url: /
jboss:
- description: jboss default http console
  port: 9990
  type: http
  url: /console
  version: '>=7.0'
- description: jboss cli console
  port: 9999
  type: telnet
  url: null
  version: '>=7.0'
- description: jboss console
  port: 8080
  type: http
  url: /web-console
  version: <=6.0
- description: jboss console
  port: 8080
  type: http
  url: /jmx-console
  version: <=6.0
- description: jboss jmx http console
  port: 8080
  type: http
  url: /invoker/JMXInvokerServlet
  version: <=6.0
resin:
- description: resin admin console
  port: 8080
  type: http
  url: /resin-admin
tomcat:
- description: tomcat default console
  password: tomcat
  port: 8080
  type: http
  url: /manager
  user: tomcat
weblogic:
- description: weblogic default console
  port: 7001
  type: http
  url: /console
websphere:
- description: websphere default console
  port: 9043
  type: https
  url: /ibm/console/logon.jsp
