######################################################################
#Wiper, an assistant tool for web penetration test.
#Copyright (c) 2014-2015 alpha1e0
#See the file COPYING for copying detail
######################################################################

#https://www.baidu.com/s?wd=angelababy&ie=utf-8&rn=20&pn=1
baidu: 
  url: http://www.baidu.com/s
  default: #默认使用的参数
    tn: baidulocal #tn表示来源，为baidulocal时能够返回纯净的页面，便于自动化处理
    ie: utf-8
  param: #可用参数
    query: wd
    encode: ie #utf-8 gb2312
    pgsize:  #页面返回的行数，取值10-100
      key: rn
      min: 10
      max: 10
    pgnum: pn #页码
    origin: tn #搜索来源，baidulocal站内搜索，baiduhome_ph百度首页
  ghsyn: #google hacking 语法
    site: site
    title: intitle
    url: inurl
    filetype: filetype
    link: null

google:
  url: https://www.google.com/search
  default: 
    ie: utf-8
  param:
    query: q
    encode: ie
    pgsize:
      key: num
      min: 10
      max: 20
    pgnum: start
  ghsyn:
    site: site
    title: intitle
    url: inurl
    filetype: filetype
    link: link

bing:
  url: http://www.bing.com/search
  default: 
    ie: utf-8
  param:
    query: q
    encode: ie
    pgsize: 
      key: num
      min: 10
      max: 10
    pgnum: first
  ghsyn:
    site: site
    title: intitle
    url: null
    filetype: filetype
    link: null