######################################################################
# Pentestdb, a database for penetration test.
# Copyright (c) 2014-2015 alpha1e0
#===================================================
# 常用 User-Agent
######################################################################

- User-Agent: "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)"
- User-Agent: "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)"
- User-Agent: "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)"
- User-Agent: "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)"
- User-Agent: "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)"
- User-Agent: "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Maxthon;"
- User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.2)Gecko/2008070208 Firefox/3.0.1"
- User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.1)Gecko/20070309 Firefox/2.0.0.3"
- User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.1)Gecko/20070803 Firefox/1.5.0.12"
- User-Agent: "Opera/9.27 (Windows NT 5.2; U; zh-cn)"
- User-Agent: "Opera/8.0 (Macintosh; PPC Mac OS X; U; en)"
- User-Agent: "Mozilla/5.0 (Macintosh; PPC Mac OS X; U; en)Opera 8.0)"
- User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.2)AppleWebKit/525.13 (KHTML, like Gecko) Version/3.1Safari/525.13"
- User-Agent: "Mozilla/5.0 (iPhone; U; CPU like Mac OS X)AppleWebKit/420.1 (KHTML, like Gecko) Version/3.0 Mobile/4A93Safari/419.3"
- User-Agent: "Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16"
- User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/525.13 (KHTML,like Gecko) Chrome/0.2.149.27 Safari/525.13"
- User-Agent: "Mozilla/5.0 (Linux; U; Android 4.0.1; ja-jp; Galaxy Nexus Build/ITL41D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
- User-Agent: "BlackBerry9000/4.6.0.294 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/220"
- User-Agent: "Nokia6600/1.0 (4.03.24) SymbianOS/6.1 Series60/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.0"
- User-Agent: "Mozilla/5.0 (Windows; U; Windows NT 5.1; es-ES; rv:1.7.5) Gecko/20041210 Firefox/1.0"